[player1]           
Character=10e354,0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f
Direction=@10e344+40,1,0


[player1]           
Character=10e356,0,0,0,0
Direction=@10e348+40,1,0

[0]
Name=Kaede

[1]
Name=Moriya

[2]
Name=Yuki

[3]
Name=Okina

[4]
Name=Akari

[5]
Name=Juzoh

[6]
Name=Washizuka

[7]
Name=Mukuro

[8]
Name=Amano

[9]
Name=Lee

[a]
Name=Zantetsu

[b]
Name=Shigen

[c]
Name=Kagami

[d]
Name=Kojiroh

[e]
Name=Hibiki


[f]
Name=Setsuna

