[Player1]
Character=0
Direction=100a85,0,1

[Player2]
Character=0
Direction=100a85,1,0


[0]
Name=Gen-An

[1]
Name=Galford

[2]
Name=Hahomaru
Macro1Name=Senpuretsuzan
Macro1Move=D,DF,F,1
Macro2Name=Kogetsuzan
Macro2Move=F,D,DF,1

[3]
Name=Ukyo

[4]
Name=Charlotte

[5]
Name=Tam-Tam

[6]
Name=Earthquake

[7]
Name=Nakoruru

[8]
Name=Wan-Fu

[9]
Name=Jubei

[a]
Name=Hanzo

[b]
Name=Kyoshiro


[Global]
