[Player1]
Character=ff8483,0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,10,11
Direction=ff840a,1,0

[Player2]
Character=ff8883,0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,10,11
Direction=ff840a,0,1


[0]
Name=Ryu

[1]
Name=Ken

[2]
Name=Akuma

[3]
Name=Charlie

[4]
Name=Chun-Li

[5]
Name=Adon

[6]
Name=Sodom

[7]
Name=Guy

[8]
Name=Birdie

[9]
Name=Rose

[a]
Name=M.Bison

[b]
Name=Sagat

[c]
Name=Dan

[d]
Name=Sakura

[e]
Name=Rolento

[f]
Name=Dhalsim

[10]
Name=Zangief

[11]
Name=Gen
