[Player1]
Character=ff875e,0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f
Direction=ff858d,1,0

[Player2]
Character=ff8b5e,0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f
Direction=ff858d,0,1



[0]
Name=Ryu

[1]
Name=E. Honda

[2]
Name=Blanka

[3]
Name=Guile

[4]
Name=Ken

[5]
Name=Chun-Li

[6]
Name=Zangief

[7]
Name=Dhalsim

[8]
Name=M.Bison

[9]
Name=Sagat

[a]
Name=Balrog

[b]
Name=Vega

[c]
Name=Cammy

[d]
Name=T.Hawk

[e]
Name=Fei Long

[f]
Name=Dee Jay
