[Player1]
Character=ff8783,0,1,2,3,4,5,6,7,8,9,a,c,d,e,f,12,18
Direction=ff8521,1,0

[Player2]
Character=ff8b83,0,1,2,3,4,5,6,7,8,9,a,c,d,e,f,12,18
Direction=ff8521,0,1

[0]
Name=Bulleta

[1]
Name=Demitri

[2]
Name=Gallon

[3]
Name=Victor

[4]
Name=Zabel

[5]
Name=Morrigan

[6]
Name=Anakaris

[7]
Name=Felicia

[8]
Name=Bishamon

[9]
Name=Aulbath

[a]
Name=Sasquatch

[c]
Name=Q-Bee

[d]
Name=Lei-Lei

[e]
Name=Lilith

[f]
Name=Jedah

[12]
Name=Dark Gallon

[18]
Name=Oboro Bishamon






